# load_config: optim/configs/default.yml

gpu: '0'
savepath_folder: output

template_mesh_path: data/tet/template.obj
target_mesh_path: data/tet/target.obj
template_rest_tet: data/tet/template_tet_dict.pkl

save_mesh_per_iter: 1000

optim: tet
optimizer: sgd
sgd_iter: 4000 #4000

lr: 0.1
iterations: 1


simplify_mesh_v: 4000
THRES_CORRES: 30
BATCH_SIZE: 1

# loss 
term_weight:
  attach: 0.0
  data: 2.0
  data_continue: 0
  data_normal: 2.0
  p2face: 0.0
  p2face_double: 0.0
  tsdf: 0.0
  smooth: 0.5
  edge: 0.5
  normal: 0.01
  laplacian: 0.1
  nh: 1.0
  collision: 1.0
  self_collision: 1.0
  link: 0.0
  hard: 0.0
  nh_max: 0
angle_filter: 90
distance_filter: 100

# smooth_sigma: 15
smooth_sigma: 2

nh_E: 10
nh_p: 0.4
# nh_p: 0.49

# contact, larger means more contact, less collision
contact_thres: 4
contact_lab: 0.5
# contact_lab_muscle: 0.5
contact_distance_mode: "p2pl"
contact_distance_use_mean: true  # False will be sum

semantic_large_reg: 100 # 10 # 
